http:
  routers:
    pve1:
      entryPoints:
        - "https"
      # The entry in the DNS server should point to the machine running Traefik/Portainer, not the external service.
      rule: "Host(`pve1.local.mydomain.com`)"
      middlewares:
        - default-headers
      tls: {}
      service: pve1

    service1:
      entryPoints:
        - "https"
      rule: "Host(`service1.local.mydomain.com`)"
      middlewares:
        - default-headers
      tls: {}
      service: service1

  services:
    pve1:
      loadBalancer:
        servers:
          # IP address of the external machine
          - url: "https://192.168.10.4:8006"
        passHostHeader: true
    service1:
      loadBalancer:
        servers:
          - url: "http://192.168.10.5:80"
          passHostHeader: true

        

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https

    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/24"
          - "192.168.0.0/16"
          - "172.0.0.0/8"

    secured:
      chain:
        middlewares:
          - default-whitelist
          - default-headers
